import { ColDef } from '@ag-grid-community/all-modules';
import {
  CellRendererFramework,
  CheckboxMetric,
  SelectGapAndPlug,
  TextFieldMetric,
  CheckboxCheckAll,
} from './cell-renderer-framework';

export const columnDefs: ColDef[] = [
  { headerName: 'Quality Metric', field: 'metricName', width: 220 },
  { headerName: 'C3', field: 'C3', cellRendererFramework: CellRendererFramework, width: 100 },
  { headerName: 'E3', field: 'E3', cellRendererFramework: CellRendererFramework, width: 100 },
  { headerName: 'G3', field: 'G3', cellRendererFramework: CellRendererFramework, width: 100 },
  { headerName: 'C12', field: 'C12', cellRendererFramework: CellRendererFramework, width: 100 },
  { headerName: 'E12', field: 'E12', cellRendererFramework: CellRendererFramework, width: 100 },
  { headerName: 'G12', field: 'G12', cellRendererFramework: CellRendererFramework, width: 100 },
  { headerName: 'C14', field: 'C14', cellRendererFramework: CellRendererFramework, width: 100 },
  { headerName: 'E14', field: 'E14', cellRendererFramework: CellRendererFramework, width: 100 },
  { headerName: 'G14', field: 'G14', cellRendererFramework: CellRendererFramework, width: 100 },
  { headerName: 'C21', field: 'C21', cellRendererFramework: CellRendererFramework, width: 100 },
  { headerName: 'E21', field: 'E21', cellRendererFramework: CellRendererFramework, width: 100 },
  { headerName: 'G21', field: 'G21', cellRendererFramework: CellRendererFramework, width: 100 },
  { headerName: 'Check All', field: 'checkAll', cellRendererFramework: CellRendererFramework, width: 100 },
];

export const rowConfig = {
  seedlingCount: {
    label: 'Seedling Count*',
    noRender: 'checkAll',
    component: TextFieldMetric,
  },
  gapPlug: {
    label: 'Gap & Plug',
    noRender: 'checkAll',
    component: SelectGapAndPlug,
  },
  underdevelopedShoot: {
    label: 'Underdeveloped Shoot',
    component: CheckboxMetric,
  },
  overdevelopedShoot: {
    label: 'Overdeveloped Shoot',
    component: CheckboxMetric,
  },
  leggy: {
    label: 'Leggy',
    component: CheckboxMetric,
  },
  rootDiscoloration: {
    label: 'Root Discoloration',
    component: CheckboxMetric,
  },
  leafDiscoloration: {
    label: 'Leaf Discoloration',
    component: CheckboxMetric,
  },
  dryPlug: {
    label: 'Dry Plug',
    component: CheckboxMetric,
  },
  oversaturatedPlug: {
    label: 'Oversaturated Plug',
    component: CheckboxMetric,
  },
  mold: {
    label: 'Mold',
    component: CheckboxMetric,
  },
  incorrectSku: {
    label: 'Incorrect SKU',
    component: CheckboxMetric,
  },
  injuriousForeignMaterial: {
    label: 'Injurious Foreign Material',
    component: CheckboxMetric,
  },
};

export const rowData: any[] = [
  {
    metricName: rowConfig.seedlingCount.label,
    C3: 1,
    E3: 2,
    G3: 3,
    C12: undefined,
    E12: undefined,
    G12: undefined,
    C14: undefined,
    E14: undefined,
    G14: undefined,
    C21: undefined,
    E21: undefined,
    G21: undefined,
  },
  {
    metricName: rowConfig.gapPlug.label,
    C3: 'low',
    E3: 'medium',
    G3: undefined,
    C12: undefined,
    E12: undefined,
    G12: undefined,
    C14: undefined,
    E14: undefined,
    G14: undefined,
    C21: undefined,
    E21: undefined,
    G21: undefined,
  },
  {
    metricName: rowConfig.underdevelopedShoot.label,
    C3: true,
    E3: true,
    G3: true,
    C12: true,
    E12: true,
    G12: true,
    C14: true,
    E14: true,
    G14: true,
    C21: true,
    E21: true,
    G21: true,
  },
  {
    metricName: rowConfig.overdevelopedShoot.label,
    C3: undefined,
    E3: undefined,
    G3: undefined,
    C12: undefined,
    E12: undefined,
    G12: undefined,
    C14: undefined,
    E14: undefined,
    G14: undefined,
    C21: undefined,
    E21: undefined,
    G21: undefined,
  },
  {
    metricName: rowConfig.leggy.label,
    C3: undefined,
    E3: undefined,
    G3: undefined,
    C12: undefined,
    E12: undefined,
    G12: undefined,
    C14: undefined,
    E14: undefined,
    G14: undefined,
    C21: undefined,
    E21: undefined,
    G21: undefined,
  },
  {
    metricName: rowConfig.rootDiscoloration.label,
    C3: undefined,
    E3: undefined,
    G3: undefined,
    C12: undefined,
    E12: undefined,
    G12: undefined,
    C14: undefined,
    E14: undefined,
    G14: undefined,
    C21: undefined,
    E21: undefined,
    G21: undefined,
  },
  {
    metricName: rowConfig.leafDiscoloration.label,
    C3: true,
    E3: true,
    G3: undefined,
    C12: undefined,
    E12: undefined,
    G12: undefined,
    C14: undefined,
    E14: undefined,
    G14: undefined,
    C21: undefined,
    E21: undefined,
    G21: undefined,
  },
  {
    metricName: rowConfig.dryPlug.label,
    C3: undefined,
    E3: undefined,
    G3: undefined,
    C12: undefined,
    E12: undefined,
    G12: undefined,
    C14: undefined,
    E14: undefined,
    G14: undefined,
    C21: undefined,
    E21: undefined,
    G21: undefined,
  },
  {
    metricName: rowConfig.oversaturatedPlug.label,
    checkAll: true,
    C3: undefined,
    E3: undefined,
    G3: undefined,
    C12: undefined,
    E12: undefined,
    G12: undefined,
    C14: undefined,
    E14: undefined,
    G14: undefined,
    C21: undefined,
    E21: undefined,
    G21: undefined,
  },
  {
    metricName: rowConfig.mold.label,
    C3: undefined,
    E3: undefined,
    G3: undefined,
    C12: undefined,
    E12: undefined,
    G12: undefined,
    C14: undefined,
    E14: undefined,
    G14: undefined,
    C21: undefined,
    E21: undefined,
    G21: undefined,
  },
  {
    metricName: rowConfig.incorrectSku.label,
    C3: undefined,
    E3: undefined,
    G3: undefined,
    C12: undefined,
    E12: undefined,
    G12: undefined,
    C14: undefined,
    E14: undefined,
    G14: undefined,
    C21: undefined,
    E21: undefined,
    G21: undefined,
  },
  {
    metricName: rowConfig.injuriousForeignMaterial.label,
    C3: undefined,
    E3: undefined,
    G3: undefined,
    C12: undefined,
    E12: undefined,
    G12: undefined,
    C14: undefined,
    E14: undefined,
    G14: undefined,
    C21: undefined,
    E21: undefined,
    G21: undefined,
  },
];
